<a href="https://colab.research.google.com/github/silverya/DeepLearning_for_everyone/blob/main/%EB%AA%A8%EB%91%90%EB%A5%BC_%EC%9C%84%ED%95%9C_%EB%94%A5%EB%9F%AC%EB%8B%9D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. simple linear regression LAB**

In [2]:
import tensorflow as tf

H(x) = Wx + b

In [3]:
x_data = [1,2,3,4,5]
y_data = [1,2,3,4,5]

In [4]:
W = tf.Variable(2.9) # 초기값
b = tf.Variable(0.5) # 초기값

In [5]:
hypothesis = W*x_data+b

In [6]:
print(hypothesis)

tf.Tensor([ 3.4       6.3       9.200001 12.1      15.      ], shape=(5,), dtype=float32)


In [7]:
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

In [8]:
print(cost)

tf.Tensor(45.660004, shape=(), dtype=float32)


In [9]:
v = [1.,2.,3.,4.]
tf.reduce_mean(v)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [11]:
tf.square(3) # 제곱 값

<tf.Tensor: shape=(), dtype=int32, numpy=9>

Gradient descent

In [19]:
learning_rate = 0.01

In [20]:
with tf.GradientTape() as tape:
    hypothesis = W*x_data+b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))

W_grad, b_grad = tape.gradient(cost, [W,b])

W.assign_sub(learning_rate * W_grad)     # A.assign_sub(B) A = A-B
b.assign_sub(learning_rate * b_grad)
  

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=0.376>

In [16]:
W = tf.Variable(2.9) # 초기값
b = tf.Variable(0.5) # 초기값

Full code

In [22]:
import tensorflow as tf

# data
x_data = [1,2,3,4,5]
y_data = [1,2,3,4,5]

# W, b initialize
W = tf.Variable(2.9)
b = tf.Variable(0.5)

learning_rate = 0.01

for i in range(100+1):  # W,b update
  # Gradient descent
  with tf.GradientTape() as tape:
    hypothesis = W*x_data+b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))

  W_grad, b_grad = tape.gradient(cost, [W,b])

  W.assign_sub(learning_rate * W_grad)     # A.assign_sub(B) A = A-B
  b.assign_sub(learning_rate * b_grad)

  if i % 10 == 0:
    print("{:5}|{:10.4}|{:10.6f}".format(i,W.numpy(),b.numpy(),cost))
    

    0|     2.452|  0.376000
   10|     1.104|  0.003398
   20|     1.013| -0.020915
   30|     1.007| -0.021845
   40|     1.006| -0.021227
   50|     1.006| -0.020527
   60|     1.005| -0.019844
   70|     1.005| -0.019183
   80|     1.005| -0.018544
   90|     1.005| -0.017927
  100|     1.005| -0.017330


**2. Linear regression and How to minimize cost LAB**

cost function in pure Python

In [26]:
import numpy as np

In [27]:
X = np.array([1,2,3])
Y = np.array([1,2,3])

In [28]:
def cost_func(W,X,Y):
    c= 0
    for i in range(len(X)):
        c += (W*X[i]-Y[i])**2
    return c/len(X)     

In [29]:
for feed_W in np.linspace(-3,5,num=15):
    curr_cost = cost_func(feed_W,X,Y)
    print("{:6.3f}|{:10.5f}".format(feed_W, curr_cost))

-3.000|  74.66667
-2.429|  54.85714
-1.857|  38.09524
-1.286|  24.38095
-0.714|  13.71429
-0.143|   6.09524
 0.429|   1.52381
 1.000|   0.00000
 1.571|   1.52381
 2.143|   6.09524
 2.714|  13.71429
 3.286|  24.38095
 3.857|  38.09524
 4.429|  54.85714
 5.000|  74.66667


Gradient descent